RestaurauntWebApp/RestaurauntWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurauntWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RestaurauntWebApp/RestaurauntWebApp/Controllers/RestaurauntController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurauntLibrary;


namespace RestaurauntWebApp.Controllers
{
    public class RestaurauntController : Controller
    {
        //RestaurauntDataLayer.RestaurauntCRUD crud;
        //use interfaces
        //constructor
        RestaurauntLibrary.BusinessLogic bl;
       
        public RestaurauntController()
        {
            bl = new RestaurauntLibrary.BusinessLogic();
        }
        //fakedb constructor


        public ActionResult GetAll(string searchStr)
        {
            if (searchStr != null)
            {
                var result = bl.SearchRestaraunts(searchStr);
                return View(result);
            }
            else
            return View(bl.GetRestauraunts());
        }
        public ActionResult GetByName()
        {
            return View(bl.SortByName());
        }
        public ActionResult TopThree()
        {
            var rests = bl.GetRestauraunts();
            var tops = RestaurauntLibrary.BusinessLogic.TopThree(rests);
            return View(tops);
        }


        // GET: Restauraunt
        [HttpGet]
        public ActionResult Index()
        {
            List < RestaurauntLibrary.Restauraunt > rests  = bl.GetRestauraunts();
            return View("GetAll");
        }

        // GET: Restauraunt/Details/5
        public ActionResult Details(int? id)
        {
            
            return View(  bl.GetRestauraunt(id));//needs web model 
        }

        // GET: Restauraunt/Create
        public ActionResult Create()
        {
            return View();//fix later
        }

        // POST: Restauraunt/Create
        [HttpPost]
        public ActionResult Create(Restauraunt rest)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    bl.AddRestauraunt(rest);
                    return RedirectToAction("GetAll");
                }
                else
                {
                    return View(rest);
                }
                
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Restauraunt/Edit/5
        public ActionResult Edit(int id)
        {
            Restauraunt toEdit = bl.GetRestauraunt(id);
            return View(toEdit);
        }

        // POST: Restauraunt/Edit/5
        [HttpPost]
        public ActionResult Edit( Restauraunt rest)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    
                    bl.UpdateRestauraunt(rest);
                    return RedirectToAction("GetAll");
                }
                else
                {
                    return View(rest);
                }
                    
                //parameter
                
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Restauraunt/Delete/5
        public ActionResult Delete(int id)
        {
            Restauraunt toDel = bl.GetRestauraunt(id);
            return View(toDel);
        }

        // POST: Restauraunt/Delete/5
        [HttpPost]
        public ActionResult Delete(Restauraunt rest)
        {
            try
            {
                // TODO: Add delete logic here
                if (ModelState.IsValid)
                {
                    bl.DeleteRestauraunt(rest);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(rest);
                }
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

RestaurauntWebApp/RestaurauntWebApp/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurauntLibrary;

namespace RestaurauntWebApp.Controllers
{
    public class ReviewController : Controller
    {
        RestaurauntLibrary.BusinessLogic bl;
      public ReviewController()
        {
            bl = new RestaurauntLibrary.BusinessLogic();
        }
        // GET: Review
        public ActionResult RevIndex(int searchId)
        {
            // result = new List<Review>();
            var result = bl.GetReviews(searchId);

            return View(result);
        }

        // GET: Review/Details/5
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: Review/Create
        public ActionResult CreateRev(int id)
        {

            return View("RevCreate");
        }

        // POST: Review/Create
        [HttpPost]
        public ActionResult CreateRev(int id,Review rev)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    rev.RestID = id;
                    bl.AddReview(rev);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Review/Edit/5
        public ActionResult EditRev(int id)
        {
            Review toEdit = bl.GetReviewById(id);
            return View(toEdit);
        }

        // POST: Review/Edit/5
        [HttpPost]
        public ActionResult EditRev(Review rev)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    bl.UpdateReview(rev);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(rev);
                }
                    
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Review/Delete/5
        public ActionResult DeleteRev(int id)
        {
            Review toDel = bl.GetReviewById(id);
           return View();
        }

        // POST: Review/Delete/5
        [HttpPost]
        public ActionResult DeleteRev(Review toDel)
        {
            try
            {
                // TODO: Add delete logic here
                if (ModelState.IsValid)
                {
                    bl.DeleteReview(toDel.ID);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(toDel);
                }
                    
                
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

RestaurauntWebApp/RestaurauntWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>We are a bare bones Resaturaunt review web application. We make no promises that any restauraunt exists at all. Consume at your own risk.</p>

RestaurauntWebApp/RestaurauntWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    11730 Plaza America DR #205<br />
    Reston, VA 201909<br />
    <abbr title="Phone">P:</abbr>
    (703) 570-8181
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RestaurauntWebApp/RestaurauntWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>HungryEats!</h1>
    <picture>
        <img src="C:\Users\Alex\source\repos\Project 1\alex-sommer-project1\RestaurauntWebApp\RestaurauntWebApp\Images\royaltyfreesalad.jpg" alt="Foodstuff" style="width:auto;">
    </picture>
    <p class="lead">This big thing has a broken image on it.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/Create.cshtml
@model RestaurauntLibrary.Restauraunt

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enter Restauraunt Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAll","RestaurauntController")
</div>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/Delete.cshtml
@model RestaurauntLibrary.Restauraunt

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restauraunt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/Details.cshtml
@model RestaurauntLibrary.Restauraunt

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Restauraunt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Show Reviews", "AllReviews")
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "GetAll")
</p>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/Edit.cshtml
@model RestaurauntLibrary.Restauraunt

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enter New Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/GetAll.cshtml
@model IEnumerable<RestaurauntLibrary.Restauraunt>

@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Restauraunts</h2>

<form asp-controller="Restauraunt" asp-action ="GetAll">
    <p>
        Search by Name: <input type="text" name="searchStr" />
        <input type="submit" value="Search"
    </p>
</form>

<p>
    @Html.ActionLink(linkText: "Create New", actionName: "Create", controllerName: "Restauraunt") | 
    @Html.ActionLink(linkText: "Sort by Name", actionName: "GetByName", controllerName: "Restauraunt")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/GetByName.cshtml
@model IEnumerable<RestaurauntLibrary.Restauraunt>

@{
    ViewBag.Title = "GetByName";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Restauraunts</h2>

<form asp-controller="Restauraunt" asp-action="GetAll">
    <p>
        Search by Name: <input type="text" name="searchStr" />
        <input type="submit" value="Search"
    </p>
</form>

<p>
    @Html.ActionLink(linkText: "Create New", actionName: "Create", controllerName: "Restauraunt") | 
    @Html.ActionLink(linkText: "Sort by Id", actionName: "GetAll", controllerName: "Restauraunt")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

RestaurauntWebApp/RestaurauntWebApp/Views/Restauraunt/TopThree.cshtml
@model IEnumerable<RestaurauntLibrary.Restauraunt>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.ID }) |*@
            @*@Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
        </td>
    </tr>
}

</table>

RestaurauntWebApp/RestaurauntWebApp/Views/Review/DeleteRev.cshtml
@model RestaurauntLibrary.Review

@{
    ViewBag.Title = "DeleteRev";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteRev</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.RestID)
        </dt>*@

        <dd>
            @Html.DisplayFor(model => model.RestID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewerRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewerRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewerComment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewerComment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Safety", "Index", "Home")
        </div>
    }
</div>

RestaurauntWebApp/RestaurauntWebApp/Views/Review/EditRev.cshtml
@model RestaurauntLibrary.Review

@{
    ViewBag.Title = "EditRev";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditRev</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        @*<div class="form-group">
            @Html.LabelFor(model => model.RestID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerComment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerComment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerComment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RestaurauntWebApp/RestaurauntWebApp/Views/Review/RevIndex.cshtml
@model IEnumerable<RestaurauntLibrary.Review>

@{
    ViewBag.Title = "RevIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reviews for the Restauraunt</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RestID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewerRating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewerComment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RestID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewerRating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewerComment)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditRev", new { id=item.ID }) |
            @Html.ActionLink("Delete", "DeleteRev", new { id=item.ID })
        </td>
    </tr>
}

</table>

RestaurauntWebApp/RestaurauntWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HungryEats!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("All Restauraunts", "GetAll", "Restauraunt")</li>
                    <li>@Html.ActionLink("Top Restauraunts", "TopThree", "Restauraunt")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Alexander Sommer, Revature</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>